"""Remove sorttime column from submission

Revision ID: 1307b62614a4
Revises: 2180d5ecf230
Create Date: 2020-02-27 14:41:40.728000

"""

# revision identifiers, used by Alembic.
revision = '1307b62614a4'
down_revision = '5a6d74c75fa6'

from alembic import op   # lgtm[py/unused-import]
import sqlalchemy as sa  # lgtm[py/unused-import]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'sorttime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('sorttime', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
