"""Convert last_login on login  table to Datetime

Revision ID: 2e25bc9a0896
Revises: 3618355655c2
Create Date: 2020-02-27 15:02:32.668000

"""

# revision identifiers, used by Alembic.
revision = '2e25bc9a0896'
down_revision = '3618355655c2'

from alembic import op   # lgtm[py/unused-import]
import sqlalchemy as sa  # lgtm[py/unused-import]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'last_login',
               existing_type=sa.INTEGER(),
               server_default=sa.text(u'now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using=" timestamp with time zone 'epoch' + (last_login-18000) * interval '1 second';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="EXTRACT(EPOCH FROM last_login at time zone 'UTC')+18000)")
    # ### end Alembic commands ###
