"""Convert logincreate timestamps to Datetime(timzone=True)

Revision ID: 3accc3d526ba
Revises: 2e25bc9a0896
Create Date: 2020-02-27 16:06:48.018000

"""

# revision identifiers, used by Alembic.
revision = '3accc3d526ba'
down_revision = '2e25bc9a0896'

from alembic import op   # lgtm[py/unused-import]
import sqlalchemy as sa  # lgtm[py/unused-import]


def upgrade():
    op.alter_column('logincreate', 'unixtime',
               existing_type=sa.INTEGER(),
               server_default=sa.func.now(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="timestamp with time zone 'epoch' + (unixtime-18000) * interval '1 second';",
               new_column_name='timestamp')
    op.alter_column('logincreate', 'birthday',
               existing_type=sa.INTEGER(),
               server_default=sa.func.now(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="timestamp with time zone 'epoch' + (birthday-18000) * interval '1 second';")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logincreate', sa.Column('unixtime', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('logincreate', 'birthday',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('logincreate', 'timestamp')
    # ### end Alembic commands ###
