"""Convert userinfo birthday to Datetime

Revision ID: 662f0e636c29
Revises: 3accc3d526ba
Create Date: 2020-02-27 17:01:16.591000

"""

# revision identifiers, used by Alembic.
revision = '662f0e636c29'
down_revision = '3accc3d526ba'

from alembic import op   # lgtm[py/unused-import]
import sqlalchemy as sa  # lgtm[py/unused-import]


def upgrade():
    op.alter_column('userinfo', 'birthday',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="timestamp with time zone 'epoch' + (birthday-18000) * interval '1 second';")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userinfo', 'birthday',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
