"""convert suspension timestamps to DateTime

Revision ID: 7ec64b7529cc
Revises: 75bf9a322d49
Create Date: 2020-02-28 16:43:07.896000

"""

# revision identifiers, used by Alembic.
revision = '7ec64b7529cc'
down_revision = '75bf9a322d49'

from alembic import op   # lgtm[py/unused-import]
import sqlalchemy as sa  # lgtm[py/unused-import]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suspension', 'release',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="timestamp with time zone 'epoch' + (link_time-18000) * interval '1 second';")
    # ### end Alembic commands ###


def downgrade():
    pass