"""Allow index to be used for comment sorting

Revision ID: 8c2635571571
Revises: 664a23bbc217
Create Date: 2018-10-21 17:47:05.349531

"""

# revision identifiers, used by Alembic.
revision = '8c2635571571'
down_revision = '664a23bbc217'

from alembic import op   # lgtm[py/unused-import]
import sqlalchemy as sa  # lgtm[py/unused-import]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ind_charcomment_targetid_commentid', 'charcomment', ['targetid', 'commentid'], unique=False)
    op.drop_index('ind_charcomment_targetid', table_name='charcomment')
    op.create_index('ind_comments_target_sub_commentid', 'comments', ['target_sub', 'commentid'], unique=False, postgresql_where=sa.text(u'target_sub IS NOT NULL'))
    op.create_index('ind_comments_target_user_commentid', 'comments', ['target_user', 'commentid'], unique=False, postgresql_where=sa.text(u'target_user IS NOT NULL'))
    op.drop_index('ix_comments_target_sub', table_name='comments')
    op.drop_index('ix_comments_target_user', table_name='comments')
    op.create_index('ind_journalcomment_targetid_commentid', 'journalcomment', ['targetid', 'commentid'], unique=False)
    op.drop_index('ind_journalcomment_settings', table_name='journalcomment')
    op.drop_index('ind_journalcomment_targetid', table_name='journalcomment')
    op.drop_index('ind_journalcomment_targetid_settings', table_name='journalcomment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ind_journalcomment_targetid_settings', 'journalcomment', ['targetid', 'settings'], unique=False)
    op.create_index('ind_journalcomment_targetid', 'journalcomment', ['targetid'], unique=False)
    op.create_index('ind_journalcomment_settings', 'journalcomment', ['settings'], unique=False)
    op.drop_index('ind_journalcomment_targetid_commentid', table_name='journalcomment')
    op.create_index('ix_comments_target_user', 'comments', ['target_user'], unique=False)
    op.create_index('ix_comments_target_sub', 'comments', ['target_sub'], unique=False)
    op.drop_index('ind_comments_target_user_commentid', table_name='comments')
    op.drop_index('ind_comments_target_sub_commentid', table_name='comments')
    op.create_index('ind_charcomment_targetid', 'charcomment', ['targetid'], unique=False)
    op.drop_index('ind_charcomment_targetid_commentid', table_name='charcomment')
    # ### end Alembic commands ###
