"""Add a table for recommendation ratings

Revision ID: a8032ce0176f
Revises: 3f18ecfaf637
Create Date: 2017-05-13 15:16:19.754039

"""

# revision identifiers, used by Alembic.
revision = 'a8032ce0176f'
down_revision = '999833c1fcf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_rating',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('submitid', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitid'], ['submission.submitid'], name='recommendation_rating_submitid_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['login.userid'], name='recommendation_rating_userid_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid', 'submitid')
    )
    # ### end Alembic commands ###
    op.execute("""
        INSERT INTO recommendation_rating (userid, submitid, rating)
        SELECT userid, targetid, 2 FROM favorite WHERE type='s'
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_rating')
    # ### end Alembic commands ###
