"""Add journal spam filtering

Revision ID: c11501a99615
Revises: 9270baf773a5
Create Date: 2019-08-28 21:49:14.218037

"""

# revision identifiers, used by Alembic.
revision = 'c11501a99615'
down_revision = '9270baf773a5'

from alembic import op   # lgtm[py/unused-import]
import sqlalchemy as sa  # lgtm[py/unused-import]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('is_spam', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('journal', sa.Column('submitter_ip_address', sa.String(length=45), nullable=True))
    op.add_column('journal', sa.Column('submitter_user_agent_id', sa.Integer(), nullable=True))
    op.create_index('ind_journal_is_spam', 'journal', ['is_spam'], unique=False)
    op.create_foreign_key('journal_user_agent_id_fkey', 'journal', 'user_agents', ['submitter_user_agent_id'], ['user_agent_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journal_user_agent_id_fkey', 'journal', type_='foreignkey')
    op.drop_index('ind_journal_is_spam', table_name='journal')
    op.drop_column('journal', 'submitter_user_agent_id')
    op.drop_column('journal', 'submitter_ip_address')
    op.drop_column('journal', 'is_spam')
    # ### end Alembic commands ###
