version: '2'
services:

  weasyl-base:
    build:
      context: ./docker
      dockerfile: weasyl-base.docker
    image: weasyl-base

  weasyl-build:
    build:
      context: ./docker
      dockerfile: weasyl-build.docker
    image: weasyl-build
    volumes_from:
      - container:${WZL_RUNNER}:rw
    environment:
      LOCAL_USER_ID: "${LOCAL_USER_ID}"

  weasyl-app:
    build:
      context: .
      dockerfile: docker/weasyl-app.docker
    image: weasyl-app

  assets:
    build:
      context: ./docker
      dockerfile: assets.docker
    volumes:
      - assets_node_modules:/weasyl-src/node_modules
    volumes_from:
      - container:${WZL_RUNNER}:rw
    environment:
      LOCAL_USER_ID: "${LOCAL_USER_ID}"

volumes:
  assets_node_modules: {}
