"""Add missing `NOT NULL`s

Revision ID: 0958abda66cf
Revises: 3f18ecfaf637
Create Date: 2017-05-08 11:01:05.744154

"""

# revision identifiers, used by Alembic.
revision = '0958abda66cf'
down_revision = '3f18ecfaf637'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charcomment', 'targetid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charcomment', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('folder', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('forgotpassword', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('journal', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('journalcomment', 'targetid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('journalcomment', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'otherid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('siteupdate', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submission', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('siteupdate', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'otherid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('journalcomment', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('journalcomment', 'targetid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('journal', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('forgotpassword', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('folder', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charcomment', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charcomment', 'targetid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('character', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
