"""Remove dead userstats table

Revision ID: 0cd4e00bd0d9
Revises: f9226a83bbb6
Create Date: 2020-02-27 23:16:59.789000

"""

# revision identifiers, used by Alembic.
revision = '0cd4e00bd0d9'
down_revision = 'f9226a83bbb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userstats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userstats',
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_views', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('submit_views', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('followers', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('faved_works', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('journals', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('submits', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('collects', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('faves', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('characters', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userid'], [u'login.userid'], name=u'userstats_userid_fkey', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('userid', name=u'userstats_pkey')
    )
    # ### end Alembic commands ###
