"""Index sessions by user id

Revision ID: 3f18ecfaf637
Revises: e50f34d62fd2
Create Date: 2017-05-06 22:02:17.746670

"""

# revision identifiers, used by Alembic.
revision = '3f18ecfaf637'
down_revision = 'e50f34d62fd2'

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ind_sessions_userid', 'sessions', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ind_sessions_userid', table_name='sessions')
    # ### end Alembic commands ###
