"""Deferrable foreign keys, revisited cascade

Revision ID: 5a073c92aab9
Revises: e63643652458
Create Date: 2025-07-23 19:52:31.899398

"""

# revision identifiers, used by Alembic.
revision = '5a073c92aab9'
down_revision = 'e63643652458'

from alembic import op


def upgrade():
    op.drop_constraint('api_tokens_userid_fkey', 'api_tokens', type_='foreignkey')
    op.create_foreign_key('api_tokens_userid_fkey', 'api_tokens', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('artist_optout_tags_tagid_fkey', 'artist_optout_tags', type_='foreignkey')
    op.drop_constraint('artist_optout_tags_targetid_fkey', 'artist_optout_tags', type_='foreignkey')
    op.create_foreign_key('artist_optout_tags_tagid_fkey', 'artist_optout_tags', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.create_foreign_key('artist_optout_tags_targetid_fkey', 'artist_optout_tags', 'login', ['targetid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('artist_preferred_tags_targetid_fkey', 'artist_preferred_tags', type_='foreignkey')
    op.drop_constraint('artist_preferred_tags_tagid_fkey', 'artist_preferred_tags', type_='foreignkey')
    op.create_foreign_key('artist_preferred_tags_targetid_fkey', 'artist_preferred_tags', 'login', ['targetid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('artist_preferred_tags_tagid_fkey', 'artist_preferred_tags', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.drop_constraint('authbcrypt_userid_fkey', 'authbcrypt', type_='foreignkey')
    op.create_foreign_key('authbcrypt_userid_fkey', 'authbcrypt', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('blocktag_userid_fkey', 'blocktag', type_='foreignkey')
    op.drop_constraint('blocktag_tagid_fkey', 'blocktag', type_='foreignkey')
    op.create_foreign_key('blocktag_userid_fkey', 'blocktag', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('blocktag_tagid_fkey', 'blocktag', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.drop_constraint('fursona_userid_fkey', 'character', type_='foreignkey')
    op.create_foreign_key('character_userid_fkey', 'character', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('charcomment_targetid_fkey', 'charcomment', type_='foreignkey')
    op.drop_constraint('charcomment_hidden_by_fkey', 'charcomment', type_='foreignkey')
    op.drop_constraint('charcomment_userid_fkey', 'charcomment', type_='foreignkey')
    op.create_foreign_key('charcomment_hidden_by_fkey', 'charcomment', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.create_foreign_key('charcomment_targetid_fkey', 'charcomment', 'character', ['targetid'], ['charid'], deferrable=True)
    op.create_foreign_key('charcomment_userid_fkey', 'charcomment', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('collection_submitid_fkey', 'collection', type_='foreignkey')
    op.drop_constraint('collection_userid_fkey', 'collection', type_='foreignkey')
    op.create_foreign_key('collection_submitid_fkey', 'collection', 'submission', ['submitid'], ['submitid'], deferrable=True)
    op.create_foreign_key('collection_userid_fkey', 'collection', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('comments_target_user_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_hidden_by_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_target_sub_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_parentid_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_userid_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key('comments_userid_fkey', 'comments', 'login', ['userid'], ['userid'], deferrable=True)
    op.create_foreign_key('comments_hidden_by_fkey', 'comments', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.create_foreign_key('comments_target_sub_fkey', 'comments', 'submission', ['target_sub'], ['submitid'], deferrable=True)
    op.create_foreign_key('comments_target_user_fkey', 'comments', 'login', ['target_user'], ['userid'], deferrable=True)
    op.create_foreign_key('comments_parentid_fkey', 'comments', 'comments', ['parentid'], ['commentid'], deferrable=True)
    op.drop_constraint('commishclass_userid_fkey', 'commishclass', type_='foreignkey')
    op.create_foreign_key('commishclass_userid_fkey', 'commishclass', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('commishdesc_userid_fkey', 'commishdesc', type_='foreignkey')
    op.create_foreign_key('commishdesc_userid_fkey', 'commishdesc', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('commishprice_userid_fkey', 'commishprice', type_='foreignkey')
    op.create_foreign_key('commishprice_userid_fkey', 'commishprice', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('emailblacklist_userid_fkey', 'emailblacklist', type_='foreignkey')
    op.create_foreign_key('emailblacklist_userid_fkey', 'emailblacklist', 'login', ['added_by'], ['userid'], deferrable=True)
    op.drop_constraint('emailverify_userid_fkey', 'emailverify', type_='foreignkey')
    op.create_foreign_key('emailverify_userid_fkey', 'emailverify', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('favorite_userid_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_userid_fkey', 'favorite', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('folder_userid_fkey', 'folder', type_='foreignkey')
    op.create_foreign_key('folder_userid_fkey', 'folder', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('frienduser_userid_fkey', 'frienduser', type_='foreignkey')
    op.drop_constraint('frienduser_otherid_fkey', 'frienduser', type_='foreignkey')
    op.create_foreign_key('frienduser_userid_fkey', 'frienduser', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('frienduser_otherid_fkey', 'frienduser', 'login', ['otherid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('globally_restricted_tags_tagid_fkey', 'globally_restricted_tags', type_='foreignkey')
    op.drop_constraint('globally_restricted_tags_userid_fkey', 'globally_restricted_tags', type_='foreignkey')
    op.create_foreign_key('globally_restricted_tags_userid_fkey', 'globally_restricted_tags', 'login', ['userid'], ['userid'], deferrable=True)
    op.create_foreign_key('globally_restricted_tags_tagid_fkey', 'globally_restricted_tags', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.drop_constraint('google_doc_embeds_submitid_fkey', 'google_doc_embeds', type_='foreignkey')
    op.create_foreign_key('google_doc_embeds_submitid_fkey', 'google_doc_embeds', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('ignoreuser_userid_fkey', 'ignoreuser', type_='foreignkey')
    op.drop_constraint('ignoreuser_otherid_fkey', 'ignoreuser', type_='foreignkey')
    op.create_foreign_key('ignoreuser_userid_fkey', 'ignoreuser', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('ignoreuser_otherid_fkey', 'ignoreuser', 'login', ['otherid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('journal_user_agent_id_fkey', 'journal', type_='foreignkey')
    op.drop_constraint('journal_userid_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key('journal_userid_fkey', 'journal', 'login', ['userid'], ['userid'], deferrable=True)
    op.create_foreign_key('journal_user_agent_id_fkey', 'journal', 'user_agents', ['submitter_user_agent_id'], ['user_agent_id'], deferrable=True)
    op.drop_constraint('journalcomment_userid_fkey', 'journalcomment', type_='foreignkey')
    op.drop_constraint('journalcomment_hidden_by_fkey', 'journalcomment', type_='foreignkey')
    op.drop_constraint('journalcomment_targetid_fkey', 'journalcomment', type_='foreignkey')
    op.create_foreign_key('journalcomment_targetid_fkey', 'journalcomment', 'journal', ['targetid'], ['journalid'], deferrable=True)
    op.create_foreign_key('journalcomment_hidden_by_fkey', 'journalcomment', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.create_foreign_key('journalcomment_userid_fkey', 'journalcomment', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('login_last_read_updateid_fkey', 'login', type_='foreignkey')
    op.drop_constraint('login_voucher_fkey', 'login', type_='foreignkey')
    op.create_foreign_key('login_last_read_updateid_fkey', 'login', 'siteupdate', ['last_read_updateid'], ['updateid'], deferrable=True)
    op.create_foreign_key('login_voucher_fkey', 'login', 'login', ['voucher'], ['userid'], deferrable=True)
    op.drop_constraint('message_userid_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_otherid_fkey', 'message', type_='foreignkey')
    op.create_foreign_key('message_userid_fkey', 'message', 'login', ['userid'], ['userid'], deferrable=True)
    op.create_foreign_key('message_otherid_fkey', 'message', 'login', ['otherid'], ['userid'], deferrable=True)
    op.drop_constraint('oauth_bearer_tokens_userid_fkey', 'oauth_bearer_tokens', type_='foreignkey')
    op.drop_constraint('oauth_bearer_tokens_clientid_fkey', 'oauth_bearer_tokens', type_='foreignkey')
    op.create_foreign_key('oauth_bearer_tokens_userid_fkey', 'oauth_bearer_tokens', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('oauth_bearer_tokens_clientid_fkey', 'oauth_bearer_tokens', 'oauth_consumers', ['clientid'], ['clientid'], deferrable=True)
    op.drop_constraint('oauth_consumers_owner_fkey', 'oauth_consumers', type_='foreignkey')
    op.create_foreign_key('oauth_consumers_owner_fkey', 'oauth_consumers', 'login', ['ownerid'], ['userid'], deferrable=True)
    op.drop_constraint('permaban_userid_fkey', 'permaban', type_='foreignkey')
    op.create_foreign_key('permaban_userid_fkey', 'permaban', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('permitted_senders_sender_fkey', 'permitted_senders', type_='foreignkey')
    op.drop_constraint('permitted_senders_userid_fkey', 'permitted_senders', type_='foreignkey')
    op.create_foreign_key('permitted_senders_sender_fkey', 'permitted_senders', 'login', ['sender'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('permitted_senders_userid_fkey', 'permitted_senders', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('profile_userid_fkey', 'profile', type_='foreignkey')
    op.create_foreign_key('profile_userid_fkey', 'profile', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('report_target_user_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_comment_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_sub_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_journal_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_closerid_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_char_fkey', 'report', type_='foreignkey')
    op.create_foreign_key('report_target_comment_fkey', 'report', 'comments', ['target_comment'], ['commentid'], deferrable=True)
    op.create_foreign_key('report_target_sub_fkey', 'report', 'submission', ['target_sub'], ['submitid'], deferrable=True)
    op.create_foreign_key('report_target_journal_fkey', 'report', 'journal', ['target_journal'], ['journalid'], deferrable=True)
    op.create_foreign_key('report_target_user_fkey', 'report', 'login', ['target_user'], ['userid'], deferrable=True)
    op.create_foreign_key('report_target_char_fkey', 'report', 'character', ['target_char'], ['charid'], deferrable=True)
    op.create_foreign_key('report_closerid_fkey', 'report', 'login', ['closerid'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.drop_constraint('reportcomment_userid_fkey', 'reportcomment', type_='foreignkey')
    op.drop_constraint('reportcomment_reportid_fkey', 'reportcomment', type_='foreignkey')
    op.create_foreign_key('reportcomment_userid_fkey', 'reportcomment', 'login', ['userid'], ['userid'], deferrable=True)
    op.create_foreign_key('reportcomment_reportid_fkey', 'reportcomment', 'report', ['reportid'], ['reportid'], deferrable=True)
    op.drop_constraint('searchmapchar_added_by_fkey', 'searchmapchar', type_='foreignkey')
    op.drop_constraint('searchmapchar_targetid_fkey', 'searchmapchar', type_='foreignkey')
    op.drop_constraint('searchmapchar_tagid_fkey', 'searchmapchar', type_='foreignkey')
    op.create_foreign_key('searchmapchar_added_by_fkey', 'searchmapchar', 'login', ['added_by'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.create_foreign_key('searchmapchar_targetid_fkey', 'searchmapchar', 'character', ['targetid'], ['charid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('searchmapchar_tagid_fkey', 'searchmapchar', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.drop_constraint('searchmapjournal_targetid_fkey', 'searchmapjournal', type_='foreignkey')
    op.drop_constraint('searchmapjournal_tagid_fkey', 'searchmapjournal', type_='foreignkey')
    op.drop_constraint('searchmapjournal_added_by_fkey', 'searchmapjournal', type_='foreignkey')
    op.create_foreign_key('searchmapjournal_targetid_fkey', 'searchmapjournal', 'journal', ['targetid'], ['journalid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('searchmapjournal_tagid_fkey', 'searchmapjournal', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.create_foreign_key('searchmapjournal_added_by_fkey', 'searchmapjournal', 'login', ['added_by'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.drop_constraint('searchmapsubmit_targetid_fkey', 'searchmapsubmit', type_='foreignkey')
    op.drop_constraint('searchmapsubmit_tagid_fkey', 'searchmapsubmit', type_='foreignkey')
    op.drop_constraint('searchmapsubmit_added_by_fkey', 'searchmapsubmit', type_='foreignkey')
    op.create_foreign_key('searchmapsubmit_tagid_fkey', 'searchmapsubmit', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.create_foreign_key('searchmapsubmit_targetid_fkey', 'searchmapsubmit', 'submission', ['targetid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('searchmapsubmit_added_by_fkey', 'searchmapsubmit', 'login', ['added_by'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.drop_constraint('sessions_user_agent_id_fkey', 'sessions', type_='foreignkey')
    op.drop_constraint('sessions_userid_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_agent_id_fkey', 'sessions', 'user_agents', ['user_agent_id'], ['user_agent_id'], deferrable=True)
    op.create_foreign_key('sessions_userid_fkey', 'sessions', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('siteupdate_userid_fkey', 'siteupdate', type_='foreignkey')
    op.create_foreign_key('siteupdate_userid_fkey', 'siteupdate', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('siteupdatecomment_userid_fkey', 'siteupdatecomment', type_='foreignkey')
    op.drop_constraint('siteupdatecomment_parentid_fkey', 'siteupdatecomment', type_='foreignkey')
    op.drop_constraint('siteupdatecomment_hidden_by_fkey', 'siteupdatecomment', type_='foreignkey')
    op.drop_constraint('siteupdatecomment_targetid_fkey', 'siteupdatecomment', type_='foreignkey')
    op.create_foreign_key('siteupdatecomment_userid_fkey', 'siteupdatecomment', 'login', ['userid'], ['userid'], deferrable=True)
    op.create_foreign_key('siteupdatecomment_parentid_fkey', 'siteupdatecomment', 'siteupdatecomment', ['targetid', 'parentid'], ['targetid', 'commentid'], deferrable=True)
    op.create_foreign_key('siteupdatecomment_hidden_by_fkey', 'siteupdatecomment', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL', deferrable=True)
    op.create_foreign_key('siteupdatecomment_targetid_fkey', 'siteupdatecomment', 'siteupdate', ['targetid'], ['updateid'], deferrable=True)
    op.drop_constraint('submission_agent_id_fkey', 'submission', type_='foreignkey')
    op.drop_constraint('submission_folderid_fkey', 'submission', type_='foreignkey')
    op.drop_constraint('submission_userid_fkey', 'submission', type_='foreignkey')
    op.create_foreign_key('submission_userid_fkey', 'submission', 'login', ['userid'], ['userid'], deferrable=True)
    op.create_foreign_key('submission_agent_id_fkey', 'submission', 'user_agents', ['submitter_user_agent_id'], ['user_agent_id'], deferrable=True)
    op.create_foreign_key('submission_folderid_fkey', 'submission', 'folder', ['folderid'], ['folderid'], ondelete='SET NULL', deferrable=True)
    op.drop_constraint('submission_media_links_mediaid_fkey', 'submission_media_links', type_='foreignkey')
    op.drop_constraint('submission_media_links_submitid_fkey', 'submission_media_links', type_='foreignkey')
    op.create_foreign_key('submission_media_links_mediaid_fkey', 'submission_media_links', 'media', ['mediaid'], ['mediaid'], deferrable=True)
    op.create_foreign_key('submission_media_links_submitid_fkey', 'submission_media_links', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('submission_tags_submitid_fkey', 'submission_tags', type_='foreignkey')
    op.create_foreign_key('submission_tags_submitid_fkey', 'submission_tags', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('suspension_userid_fkey', 'suspension', type_='foreignkey')
    op.create_foreign_key('suspension_userid_fkey', 'suspension', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('tag_suggestion_feedback_character_userid_fkey', 'tag_suggestion_feedback_character', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_character_targetid_fkey', 'tag_suggestion_feedback_character', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_character_tagid_fkey', 'tag_suggestion_feedback_character', type_='foreignkey')
    op.create_foreign_key('tag_suggestion_feedback_character_userid_fkey', 'tag_suggestion_feedback_character', 'login', ['userid'], ['userid'], ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('tag_suggestion_feedback_character_tagid_fkey', 'tag_suggestion_feedback_character', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.create_foreign_key('tag_suggestion_feedback_character_targetid_fkey', 'tag_suggestion_feedback_character', 'character', ['targetid'], ['charid'], ondelete='CASCADE', deferrable=True)
    op.drop_constraint('tag_suggestion_feedback_journal_tagid_fkey', 'tag_suggestion_feedback_journal', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_journal_userid_fkey', 'tag_suggestion_feedback_journal', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_journal_targetid_fkey', 'tag_suggestion_feedback_journal', type_='foreignkey')
    op.create_foreign_key('tag_suggestion_feedback_journal_tagid_fkey', 'tag_suggestion_feedback_journal', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.create_foreign_key('tag_suggestion_feedback_journal_userid_fkey', 'tag_suggestion_feedback_journal', 'login', ['userid'], ['userid'], ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('tag_suggestion_feedback_journal_targetid_fkey', 'tag_suggestion_feedback_journal', 'journal', ['targetid'], ['journalid'], ondelete='CASCADE', deferrable=True)
    op.drop_constraint('tag_suggestion_feedback_submission_userid_fkey', 'tag_suggestion_feedback_submission', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_submission_targetid_fkey', 'tag_suggestion_feedback_submission', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_submission_tagid_fkey', 'tag_suggestion_feedback_submission', type_='foreignkey')
    op.create_foreign_key('tag_suggestion_feedback_submission_userid_fkey', 'tag_suggestion_feedback_submission', 'login', ['userid'], ['userid'], ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('tag_suggestion_feedback_submission_targetid_fkey', 'tag_suggestion_feedback_submission', 'submission', ['targetid'], ['submitid'], ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('tag_suggestion_feedback_submission_tagid_fkey', 'tag_suggestion_feedback_submission', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.drop_constraint('tag_updates_submitid_fkey', 'tag_updates', type_='foreignkey')
    op.drop_constraint('tag_updates_userid_fkey', 'tag_updates', type_='foreignkey')
    op.create_foreign_key('tag_updates_submitid_fkey', 'tag_updates', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('tag_updates_userid_fkey', 'tag_updates', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('twofa_recovery_codes_userid_fkey', 'twofa_recovery_codes', type_='foreignkey')
    op.create_foreign_key('twofa_recovery_codes_userid_fkey', 'twofa_recovery_codes', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('user_events_userid_fkey', 'user_events', type_='foreignkey')
    op.create_foreign_key('user_events_userid_fkey', 'user_events', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('user_links_userid_fkey', 'user_links', type_='foreignkey')
    op.create_foreign_key('user_links_userid_fkey', 'user_links', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('user_media_links_userid_fkey', 'user_media_links', type_='foreignkey')
    op.drop_constraint('user_media_links_mediaid_fkey', 'user_media_links', type_='foreignkey')
    op.create_foreign_key('user_media_links_mediaid_fkey', 'user_media_links', 'media', ['mediaid'], ['mediaid'], deferrable=True)
    op.create_foreign_key('user_media_links_userid_fkey', 'user_media_links', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('user_restricted_tags_tagid_fkey', 'user_restricted_tags', type_='foreignkey')
    op.drop_constraint('user_restricted_tags_userid_fkey', 'user_restricted_tags', type_='foreignkey')
    op.create_foreign_key('user_restricted_tags_tagid_fkey', 'user_restricted_tags', 'searchtag', ['tagid'], ['tagid'], deferrable=True)
    op.create_foreign_key('user_restricted_tags_userid_fkey', 'user_restricted_tags', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('user_streams_userid_fkey', 'user_streams', type_='foreignkey')
    op.create_foreign_key('user_streams_userid_fkey', 'user_streams', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('useralias_userid_fkey', 'useralias', type_='foreignkey')
    op.create_foreign_key('useralias_userid_fkey', 'useralias', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('userinfo_userid_fkey', 'userinfo', type_='foreignkey')
    op.create_foreign_key('userinfo_userid_fkey', 'userinfo', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.drop_constraint('username_history_replaced_by_fkey', 'username_history', type_='foreignkey')
    op.drop_constraint('username_history_deactivated_by_fkey', 'username_history', type_='foreignkey')
    op.drop_constraint('username_history_userid_fkey', 'username_history', type_='foreignkey')
    op.create_foreign_key('username_history_replaced_by_fkey', 'username_history', 'login', ['replaced_by'], ['userid'], deferrable=True)
    op.create_foreign_key('username_history_deactivated_by_fkey', 'username_history', 'login', ['deactivated_by'], ['userid'], deferrable=True)
    op.create_foreign_key('username_history_userid_fkey', 'username_history', 'login', ['userid'], ['userid'], deferrable=True)
    op.drop_constraint('watchuser_otherid_fkey', 'watchuser', type_='foreignkey')
    op.drop_constraint('watchuser_userid_fkey', 'watchuser', type_='foreignkey')
    op.create_foreign_key('watchuser_userid_fkey', 'watchuser', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)
    op.create_foreign_key('watchuser_otherid_fkey', 'watchuser', 'login', ['otherid'], ['userid'], deferrable=True)
    op.drop_constraint('welcome_userid_fkey', 'welcome', type_='foreignkey')
    op.create_foreign_key('welcome_userid_fkey', 'welcome', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE', deferrable=True)


def downgrade():
    op.drop_constraint('welcome_userid_fkey', 'welcome', type_='foreignkey')
    op.create_foreign_key('welcome_userid_fkey', 'welcome', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('watchuser_otherid_fkey', 'watchuser', type_='foreignkey')
    op.drop_constraint('watchuser_userid_fkey', 'watchuser', type_='foreignkey')
    op.create_foreign_key('watchuser_userid_fkey', 'watchuser', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('watchuser_otherid_fkey', 'watchuser', 'login', ['otherid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('username_history_userid_fkey', 'username_history', type_='foreignkey')
    op.drop_constraint('username_history_deactivated_by_fkey', 'username_history', type_='foreignkey')
    op.drop_constraint('username_history_replaced_by_fkey', 'username_history', type_='foreignkey')
    op.create_foreign_key('username_history_userid_fkey', 'username_history', 'login', ['userid'], ['userid'])
    op.create_foreign_key('username_history_deactivated_by_fkey', 'username_history', 'login', ['deactivated_by'], ['userid'])
    op.create_foreign_key('username_history_replaced_by_fkey', 'username_history', 'login', ['replaced_by'], ['userid'])
    op.drop_constraint('userinfo_userid_fkey', 'userinfo', type_='foreignkey')
    op.create_foreign_key('userinfo_userid_fkey', 'userinfo', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('useralias_userid_fkey', 'useralias', type_='foreignkey')
    op.create_foreign_key('useralias_userid_fkey', 'useralias', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_streams_userid_fkey', 'user_streams', type_='foreignkey')
    op.create_foreign_key('user_streams_userid_fkey', 'user_streams', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_restricted_tags_userid_fkey', 'user_restricted_tags', type_='foreignkey')
    op.drop_constraint('user_restricted_tags_tagid_fkey', 'user_restricted_tags', type_='foreignkey')
    op.create_foreign_key('user_restricted_tags_userid_fkey', 'user_restricted_tags', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('user_restricted_tags_tagid_fkey', 'user_restricted_tags', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_media_links_userid_fkey', 'user_media_links', type_='foreignkey')
    op.drop_constraint('user_media_links_mediaid_fkey', 'user_media_links', type_='foreignkey')
    op.create_foreign_key('user_media_links_mediaid_fkey', 'user_media_links', 'media', ['mediaid'], ['mediaid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('user_media_links_userid_fkey', 'user_media_links', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_links_userid_fkey', 'user_links', type_='foreignkey')
    op.create_foreign_key('user_links_userid_fkey', 'user_links', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_events_userid_fkey', 'user_events', type_='foreignkey')
    op.create_foreign_key('user_events_userid_fkey', 'user_events', 'login', ['userid'], ['userid'])
    op.drop_constraint('twofa_recovery_codes_userid_fkey', 'twofa_recovery_codes', type_='foreignkey')
    op.create_foreign_key('twofa_recovery_codes_userid_fkey', 'twofa_recovery_codes', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('tag_updates_userid_fkey', 'tag_updates', type_='foreignkey')
    op.drop_constraint('tag_updates_submitid_fkey', 'tag_updates', type_='foreignkey')
    op.create_foreign_key('tag_updates_userid_fkey', 'tag_updates', 'login', ['userid'], ['userid'])
    op.create_foreign_key('tag_updates_submitid_fkey', 'tag_updates', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('tag_suggestion_feedback_submission_tagid_fkey', 'tag_suggestion_feedback_submission', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_submission_targetid_fkey', 'tag_suggestion_feedback_submission', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_submission_userid_fkey', 'tag_suggestion_feedback_submission', type_='foreignkey')
    op.create_foreign_key('tag_suggestion_feedback_submission_tagid_fkey', 'tag_suggestion_feedback_submission', 'searchtag', ['tagid'], ['tagid'])
    op.create_foreign_key('tag_suggestion_feedback_submission_targetid_fkey', 'tag_suggestion_feedback_submission', 'submission', ['targetid'], ['submitid'], ondelete='CASCADE')
    op.create_foreign_key('tag_suggestion_feedback_submission_userid_fkey', 'tag_suggestion_feedback_submission', 'login', ['userid'], ['userid'], ondelete='CASCADE')
    op.drop_constraint('tag_suggestion_feedback_journal_tagid_fkey', 'tag_suggestion_feedback_journal', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_journal_targetid_fkey', 'tag_suggestion_feedback_journal', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_journal_userid_fkey', 'tag_suggestion_feedback_journal', type_='foreignkey')
    op.create_foreign_key('tag_suggestion_feedback_journal_targetid_fkey', 'tag_suggestion_feedback_journal', 'journal', ['targetid'], ['journalid'], ondelete='CASCADE')
    op.create_foreign_key('tag_suggestion_feedback_journal_userid_fkey', 'tag_suggestion_feedback_journal', 'login', ['userid'], ['userid'], ondelete='CASCADE')
    op.create_foreign_key('tag_suggestion_feedback_journal_tagid_fkey', 'tag_suggestion_feedback_journal', 'searchtag', ['tagid'], ['tagid'])
    op.drop_constraint('tag_suggestion_feedback_character_tagid_fkey', 'tag_suggestion_feedback_character', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_character_targetid_fkey', 'tag_suggestion_feedback_character', type_='foreignkey')
    op.drop_constraint('tag_suggestion_feedback_character_userid_fkey', 'tag_suggestion_feedback_character', type_='foreignkey')
    op.create_foreign_key('tag_suggestion_feedback_character_tagid_fkey', 'tag_suggestion_feedback_character', 'searchtag', ['tagid'], ['tagid'])
    op.create_foreign_key('tag_suggestion_feedback_character_targetid_fkey', 'tag_suggestion_feedback_character', 'character', ['targetid'], ['charid'], ondelete='CASCADE')
    op.create_foreign_key('tag_suggestion_feedback_character_userid_fkey', 'tag_suggestion_feedback_character', 'login', ['userid'], ['userid'], ondelete='CASCADE')
    op.drop_constraint('suspension_userid_fkey', 'suspension', type_='foreignkey')
    op.create_foreign_key('suspension_userid_fkey', 'suspension', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('submission_tags_submitid_fkey', 'submission_tags', type_='foreignkey')
    op.create_foreign_key('submission_tags_submitid_fkey', 'submission_tags', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('submission_media_links_submitid_fkey', 'submission_media_links', type_='foreignkey')
    op.drop_constraint('submission_media_links_mediaid_fkey', 'submission_media_links', type_='foreignkey')
    op.create_foreign_key('submission_media_links_submitid_fkey', 'submission_media_links', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('submission_media_links_mediaid_fkey', 'submission_media_links', 'media', ['mediaid'], ['mediaid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('submission_folderid_fkey', 'submission', type_='foreignkey')
    op.drop_constraint('submission_agent_id_fkey', 'submission', type_='foreignkey')
    op.drop_constraint('submission_userid_fkey', 'submission', type_='foreignkey')
    op.create_foreign_key('submission_userid_fkey', 'submission', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('submission_folderid_fkey', 'submission', 'folder', ['folderid'], ['folderid'], ondelete='SET NULL')
    op.create_foreign_key('submission_agent_id_fkey', 'submission', 'user_agents', ['submitter_user_agent_id'], ['user_agent_id'])
    op.drop_constraint('siteupdatecomment_targetid_fkey', 'siteupdatecomment', type_='foreignkey')
    op.drop_constraint('siteupdatecomment_hidden_by_fkey', 'siteupdatecomment', type_='foreignkey')
    op.drop_constraint('siteupdatecomment_parentid_fkey', 'siteupdatecomment', type_='foreignkey')
    op.drop_constraint('siteupdatecomment_userid_fkey', 'siteupdatecomment', type_='foreignkey')
    op.create_foreign_key('siteupdatecomment_targetid_fkey', 'siteupdatecomment', 'siteupdate', ['targetid'], ['updateid'])
    op.create_foreign_key('siteupdatecomment_hidden_by_fkey', 'siteupdatecomment', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL')
    op.create_foreign_key('siteupdatecomment_parentid_fkey', 'siteupdatecomment', 'siteupdatecomment', ['targetid', 'parentid'], ['targetid', 'commentid'])
    op.create_foreign_key('siteupdatecomment_userid_fkey', 'siteupdatecomment', 'login', ['userid'], ['userid'])
    op.drop_constraint('siteupdate_userid_fkey', 'siteupdate', type_='foreignkey')
    op.create_foreign_key('siteupdate_userid_fkey', 'siteupdate', 'login', ['userid'], ['userid'])
    op.drop_constraint('sessions_userid_fkey', 'sessions', type_='foreignkey')
    op.drop_constraint('sessions_user_agent_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_userid_fkey', 'sessions', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('sessions_user_agent_id_fkey', 'sessions', 'user_agents', ['user_agent_id'], ['user_agent_id'])
    op.drop_constraint('searchmapsubmit_added_by_fkey', 'searchmapsubmit', type_='foreignkey')
    op.drop_constraint('searchmapsubmit_targetid_fkey', 'searchmapsubmit', type_='foreignkey')
    op.drop_constraint('searchmapsubmit_tagid_fkey', 'searchmapsubmit', type_='foreignkey')
    op.create_foreign_key('searchmapsubmit_added_by_fkey', 'searchmapsubmit', 'login', ['added_by'], ['userid'], ondelete='SET NULL')
    op.create_foreign_key('searchmapsubmit_tagid_fkey', 'searchmapsubmit', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('searchmapsubmit_targetid_fkey', 'searchmapsubmit', 'submission', ['targetid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('searchmapjournal_added_by_fkey', 'searchmapjournal', type_='foreignkey')
    op.drop_constraint('searchmapjournal_tagid_fkey', 'searchmapjournal', type_='foreignkey')
    op.drop_constraint('searchmapjournal_targetid_fkey', 'searchmapjournal', type_='foreignkey')
    op.create_foreign_key('searchmapjournal_added_by_fkey', 'searchmapjournal', 'login', ['added_by'], ['userid'], ondelete='SET NULL')
    op.create_foreign_key('searchmapjournal_tagid_fkey', 'searchmapjournal', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('searchmapjournal_targetid_fkey', 'searchmapjournal', 'journal', ['targetid'], ['journalid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('searchmapchar_tagid_fkey', 'searchmapchar', type_='foreignkey')
    op.drop_constraint('searchmapchar_targetid_fkey', 'searchmapchar', type_='foreignkey')
    op.drop_constraint('searchmapchar_added_by_fkey', 'searchmapchar', type_='foreignkey')
    op.create_foreign_key('searchmapchar_tagid_fkey', 'searchmapchar', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('searchmapchar_targetid_fkey', 'searchmapchar', 'character', ['targetid'], ['charid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('searchmapchar_added_by_fkey', 'searchmapchar', 'login', ['added_by'], ['userid'], ondelete='SET NULL')
    op.drop_constraint('reportcomment_reportid_fkey', 'reportcomment', type_='foreignkey')
    op.drop_constraint('reportcomment_userid_fkey', 'reportcomment', type_='foreignkey')
    op.create_foreign_key('reportcomment_reportid_fkey', 'reportcomment', 'report', ['reportid'], ['reportid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('reportcomment_userid_fkey', 'reportcomment', 'login', ['userid'], ['userid'])
    op.drop_constraint('report_closerid_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_char_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_user_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_journal_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_sub_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_target_comment_fkey', 'report', type_='foreignkey')
    op.create_foreign_key('report_target_char_fkey', 'report', 'character', ['target_char'], ['charid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('report_closerid_fkey', 'report', 'login', ['closerid'], ['userid'], ondelete='SET NULL')
    op.create_foreign_key('report_target_journal_fkey', 'report', 'journal', ['target_journal'], ['journalid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('report_target_sub_fkey', 'report', 'submission', ['target_sub'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('report_target_comment_fkey', 'report', 'comments', ['target_comment'], ['commentid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('report_target_user_fkey', 'report', 'login', ['target_user'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('profile_userid_fkey', 'profile', type_='foreignkey')
    op.create_foreign_key('profile_userid_fkey', 'profile', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('permitted_senders_userid_fkey', 'permitted_senders', type_='foreignkey')
    op.drop_constraint('permitted_senders_sender_fkey', 'permitted_senders', type_='foreignkey')
    op.create_foreign_key('permitted_senders_userid_fkey', 'permitted_senders', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('permitted_senders_sender_fkey', 'permitted_senders', 'login', ['sender'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('permaban_userid_fkey', 'permaban', type_='foreignkey')
    op.create_foreign_key('permaban_userid_fkey', 'permaban', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('oauth_consumers_owner_fkey', 'oauth_consumers', type_='foreignkey')
    op.create_foreign_key('oauth_consumers_owner_fkey', 'oauth_consumers', 'login', ['ownerid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('oauth_bearer_tokens_clientid_fkey', 'oauth_bearer_tokens', type_='foreignkey')
    op.drop_constraint('oauth_bearer_tokens_userid_fkey', 'oauth_bearer_tokens', type_='foreignkey')
    op.create_foreign_key('oauth_bearer_tokens_clientid_fkey', 'oauth_bearer_tokens', 'oauth_consumers', ['clientid'], ['clientid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('oauth_bearer_tokens_userid_fkey', 'oauth_bearer_tokens', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('message_otherid_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_userid_fkey', 'message', type_='foreignkey')
    op.create_foreign_key('message_otherid_fkey', 'message', 'login', ['otherid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('message_userid_fkey', 'message', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('login_voucher_fkey', 'login', type_='foreignkey')
    op.drop_constraint('login_last_read_updateid_fkey', 'login', type_='foreignkey')
    op.create_foreign_key('login_voucher_fkey', 'login', 'login', ['voucher'], ['userid'])
    op.create_foreign_key('login_last_read_updateid_fkey', 'login', 'siteupdate', ['last_read_updateid'], ['updateid'])
    op.drop_constraint('journalcomment_userid_fkey', 'journalcomment', type_='foreignkey')
    op.drop_constraint('journalcomment_hidden_by_fkey', 'journalcomment', type_='foreignkey')
    op.drop_constraint('journalcomment_targetid_fkey', 'journalcomment', type_='foreignkey')
    op.create_foreign_key('journalcomment_targetid_fkey', 'journalcomment', 'journal', ['targetid'], ['journalid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('journalcomment_hidden_by_fkey', 'journalcomment', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL')
    op.create_foreign_key('journalcomment_userid_fkey', 'journalcomment', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('journal_user_agent_id_fkey', 'journal', type_='foreignkey')
    op.drop_constraint('journal_userid_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key('journal_userid_fkey', 'journal', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('journal_user_agent_id_fkey', 'journal', 'user_agents', ['submitter_user_agent_id'], ['user_agent_id'])
    op.drop_constraint('ignoreuser_otherid_fkey', 'ignoreuser', type_='foreignkey')
    op.drop_constraint('ignoreuser_userid_fkey', 'ignoreuser', type_='foreignkey')
    op.create_foreign_key('ignoreuser_otherid_fkey', 'ignoreuser', 'login', ['otherid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ignoreuser_userid_fkey', 'ignoreuser', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('google_doc_embeds_submitid_fkey', 'google_doc_embeds', type_='foreignkey')
    op.create_foreign_key('google_doc_embeds_submitid_fkey', 'google_doc_embeds', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('globally_restricted_tags_tagid_fkey', 'globally_restricted_tags', type_='foreignkey')
    op.drop_constraint('globally_restricted_tags_userid_fkey', 'globally_restricted_tags', type_='foreignkey')
    op.create_foreign_key('globally_restricted_tags_userid_fkey', 'globally_restricted_tags', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('globally_restricted_tags_tagid_fkey', 'globally_restricted_tags', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('frienduser_otherid_fkey', 'frienduser', type_='foreignkey')
    op.drop_constraint('frienduser_userid_fkey', 'frienduser', type_='foreignkey')
    op.create_foreign_key('frienduser_otherid_fkey', 'frienduser', 'login', ['otherid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('frienduser_userid_fkey', 'frienduser', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('folder_userid_fkey', 'folder', type_='foreignkey')
    op.create_foreign_key('folder_userid_fkey', 'folder', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('favorite_userid_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_userid_fkey', 'favorite', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('emailverify_userid_fkey', 'emailverify', type_='foreignkey')
    op.create_foreign_key('emailverify_userid_fkey', 'emailverify', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('emailblacklist_userid_fkey', 'emailblacklist', type_='foreignkey')
    op.create_foreign_key('emailblacklist_userid_fkey', 'emailblacklist', 'login', ['added_by'], ['userid'])
    op.drop_constraint('commishprice_userid_fkey', 'commishprice', type_='foreignkey')
    op.create_foreign_key('commishprice_userid_fkey', 'commishprice', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('commishdesc_userid_fkey', 'commishdesc', type_='foreignkey')
    op.create_foreign_key('commishdesc_userid_fkey', 'commishdesc', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('commishclass_userid_fkey', 'commishclass', type_='foreignkey')
    op.create_foreign_key('commishclass_userid_fkey', 'commishclass', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('comments_parentid_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_target_user_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_target_sub_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_hidden_by_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_userid_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key('comments_userid_fkey', 'comments', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('comments_parentid_fkey', 'comments', 'comments', ['parentid'], ['commentid'])
    op.create_foreign_key('comments_target_sub_fkey', 'comments', 'submission', ['target_sub'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('comments_hidden_by_fkey', 'comments', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL')
    op.create_foreign_key('comments_target_user_fkey', 'comments', 'login', ['target_user'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('collection_userid_fkey', 'collection', type_='foreignkey')
    op.drop_constraint('collection_submitid_fkey', 'collection', type_='foreignkey')
    op.create_foreign_key('collection_userid_fkey', 'collection', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('collection_submitid_fkey', 'collection', 'submission', ['submitid'], ['submitid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('charcomment_userid_fkey', 'charcomment', type_='foreignkey')
    op.drop_constraint('charcomment_targetid_fkey', 'charcomment', type_='foreignkey')
    op.drop_constraint('charcomment_hidden_by_fkey', 'charcomment', type_='foreignkey')
    op.create_foreign_key('charcomment_userid_fkey', 'charcomment', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('charcomment_hidden_by_fkey', 'charcomment', 'login', ['hidden_by'], ['userid'], ondelete='SET NULL')
    op.create_foreign_key('charcomment_targetid_fkey', 'charcomment', 'character', ['targetid'], ['charid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('character_userid_fkey', 'character', type_='foreignkey')
    op.create_foreign_key('fursona_userid_fkey', 'character', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('blocktag_tagid_fkey', 'blocktag', type_='foreignkey')
    op.drop_constraint('blocktag_userid_fkey', 'blocktag', type_='foreignkey')
    op.create_foreign_key('blocktag_tagid_fkey', 'blocktag', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('blocktag_userid_fkey', 'blocktag', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('authbcrypt_userid_fkey', 'authbcrypt', type_='foreignkey')
    op.create_foreign_key('authbcrypt_userid_fkey', 'authbcrypt', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('artist_preferred_tags_tagid_fkey', 'artist_preferred_tags', type_='foreignkey')
    op.drop_constraint('artist_preferred_tags_targetid_fkey', 'artist_preferred_tags', type_='foreignkey')
    op.create_foreign_key('artist_preferred_tags_tagid_fkey', 'artist_preferred_tags', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('artist_preferred_tags_targetid_fkey', 'artist_preferred_tags', 'login', ['targetid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('artist_optout_tags_targetid_fkey', 'artist_optout_tags', type_='foreignkey')
    op.drop_constraint('artist_optout_tags_tagid_fkey', 'artist_optout_tags', type_='foreignkey')
    op.create_foreign_key('artist_optout_tags_targetid_fkey', 'artist_optout_tags', 'login', ['targetid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('artist_optout_tags_tagid_fkey', 'artist_optout_tags', 'searchtag', ['tagid'], ['tagid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('api_tokens_userid_fkey', 'api_tokens', type_='foreignkey')
    op.create_foreign_key('api_tokens_userid_fkey', 'api_tokens', 'login', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
