"""Add optional labels to contact links

Revision ID: a1ca3ad2ed42
Revises: 63baa2713e72
Create Date: 2024-12-15 22:29:45.794365

"""

# revision identifiers, used by Alembic.
revision = 'a1ca3ad2ed42'
down_revision = '63baa2713e72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_links', sa.Column('link_label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_links', 'link_label')
    # ### end Alembic commands ###
