"""Remove unused stream_time column from profile table

Revision ID: cc2f96b0ba35
Revises: 0cd4e00bd0d9
Create Date: 2020-02-27 23:19:49.133000

"""

# revision identifiers, used by Alembic.
revision = 'cc2f96b0ba35'
down_revision = '0cd4e00bd0d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'stream_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('stream_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
