[tool.poetry]
name = "weasyl-poetry"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
