#!/bin/sh
set -eu
exec docker run --rm -it \
    `#--runtime=runsc` \
    --security-opt=no-new-privileges \
    --user="$(id -u):$(id -g)" \
    --read-only \
    --init \
    --tmpfs=/tmp \
    "$@"
