#!/bin/sh -eu

if [ "$(whoami)" = "weasyl" ]; then
    exec "$@"
fi

if [ -n "${LOCAL_USER_ID-}" ]; then
    olduid="$(id -u weasyl)"
    if [ "${LOCAL_USER_ID}" != "${olduid}" ]; then
        echo "=== remapping weasyl (${olduid} => ${LOCAL_USER_ID})"
        usermod -ou "${LOCAL_USER_ID}" weasyl
        for dir in /appenv /weasyl-app /weasyl-src ~weasyl; do
            test -e "${dir}" \
                && find "${dir}" \( -uid "${olduid}" -o -uid 0 \) -print0 \
		    | xargs -r0 chown weasyl
        done
    fi
fi

# This MUST be two lines, or sh gets confused.
HOME=~weasyl
export HOME
exec chpst -u weasyl "$@"
