#!/bin/sh -eu

if [ -n "${LOCAL_USER_ID-}" ]; then
    olduid="$(id -u weasyl)"
    if [ "${LOCAL_USER_ID}" != "${olduid}" ]; then
        echo "=== remapping weasyl (${olduid} => ${LOCAL_USER_ID})"
        usermod -u "${LOCAL_USER_ID}" weasyl
        for dir in /appenv /weasyl-app /weasyl-src ~weasyl; do
            test -e "${dir}" \
                && find "${dir}" -uid "${olduid}" -print0 | xargs -r0 chown weasyl
        done
    fi
fi

# This MUST be two lines, or sh gets confused.
HOME=~weasyl
export HOME
exec chpst -u weasyl "$@"
