all: img/help/help-gdocs-1@2x.webp img/help/help-gdocs-2@2x.webp img/help/help-gdocs-3@2x.webp img/help/help-gdocs-4@2x.webp img/help/help-gdocs-1.webp img/help/help-gdocs-2.webp img/help/help-gdocs-3.webp img/help/help-gdocs-4.webp

img/help/help-gdocs-1@2x.webp: img/help/help-gdocs-1@2x.png
	cwebp -mt -q 100 -near_lossless 20 $< -o $@

img/help/help-gdocs-2@2x.webp: img/help/help-gdocs-2@2x.png
	cwebp -mt -q 100 -near_lossless 0 $< -o $@

img/help/help-gdocs-3@2x.webp: img/help/help-gdocs-3@2x.png
	cwebp -mt -q 100 -near_lossless 0 $< -o $@

img/help/help-gdocs-4@2x.webp: img/help/help-gdocs-4@2x.png
	cwebp -mt -q 100 -near_lossless 40 $< -o $@

img/help/help-gdocs-1.webp: img/help/help-gdocs-1.png
	cwebp -mt -q 100 -near_lossless 20 $< -o $@

img/help/help-gdocs-2.webp: img/help/help-gdocs-2.png
	cwebp -mt -q 100 -near_lossless 0 $< -o $@

img/help/help-gdocs-3.webp: img/help/help-gdocs-3.png
	cwebp -mt -q 100 -near_lossless 0 $< -o $@

img/help/help-gdocs-4.webp: img/help/help-gdocs-4.png
	cwebp -mt -q 100 -near_lossless 40 $< -o $@

.PHONY: all
