"""
Global variables of staff.

This module must be initialized by the following call:

_init_staff(directors=staff_config_dict['directors'],
            technical_staff=staff_config_dict['technical_staff'],
            admins=staff_config_dict['admins'],
            mods=staff_config_dict['mods'],
            developers=staff_config_dict['developers'])

The staff_config_dict is generated by weasyl/read_staff_yaml.py; see that file
for further information on the formatting of the dict.
"""


def _init_staff(**kwargs):
    """
    Populates staff members from passed kwargs.

    Parameters:
        directors: Array with directors
        technical_staff: Array with technical staff
        admins: array with admins
        mods: Array with mods
        developers: Array with developers
    """

    """ Directors have the same powers as admins. """
    global DIRECTORS
    DIRECTORS = frozenset(kwargs['directors'])

    """ Technical staff can moderate all content and manage all users. """
    global TECHNICAL
    TECHNICAL = frozenset(DIRECTORS.union(kwargs['technical_staff']))

    """ Site administrators can update site news and moderate user content. """
    global ADMINS
    ADMINS = frozenset(TECHNICAL.union(kwargs['admins']))

    """ Site moderators can hide submissions, manage non-admin users, etc. """
    global MODS
    MODS = frozenset(ADMINS.union(kwargs['mods']))

    """ Purely cosmetic group for users who contribute to site development. """
    global DEVELOPERS
    DEVELOPERS = frozenset(kwargs['developers'])
